name: Corep lighting
favicon: null
layout_spectrum: 0.1382768270559609
typography_spectrum: 0.23636940424330533
title: Lighting Manufacturer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.584372385405004
  lightness: 0.18120050174184144
  saturation: 0.16287907306104898
  rhythmicContrast: 0.6376929613761604
purpose: []
